# Generated by Django 3.2.5 on 2021-07-16 04:09

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_reciclaje',
            fields=[
                ('id_plan', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=30)),
                ('valor_plan', models.IntegerField()),
                ('num_retiros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(choices=[('1', 'La Serena'), ('2', 'Coquimbo')], max_length=20, null=True)),
                ('fecha_entrega', models.DateField(null=True)),
                ('rec', recurrence.fields.RecurrenceField(null=True)),
                ('plan_reciclaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion.plan_reciclaje')),
            ],
        ),
    ]
